<h1 class="h3 mb-3 font-weight-normal">Interface Administrateur</h1>

<div class="album py-5 bg-light">

  <div class="container" id="main-container">
    <form>
        <label for="inputNom" class="sr-only">Nouveau nom</label>
        <input id="inputNom" class="form-control" placeholder="Nouveau Nom" required autofocus>
        
        <label for="inputPrix" class="sr-only">Nouveau prix</label>
        <input id="inputPrix" class="form-control" placeholder="Nouveau prix" required>
        
        <label for="inputDesc" class="sr-only">Nouvelle Description</label>
        <input id="inputDesc" class="form-control" placeholder="Nouvelle Description" required>
        
        <button class="btn btn-lg btn-primary btn-block" type="submit" onclick="modifier_description()">Valider</button>
    </form>
  </div>
  
</div>
