<h1 class="h3 mb-3 font-weight-normal">Description Detaillee</h1>

<div class="album py-5 bg-light">
    
    <div class="container">
        <div class="row margin-custom">

            <div class="col">
                <img src="" alt="products details" id="img_produit">
            </div>

            <div class="col">
                <h2 class="margin-custom", id="nom_produit"></h2>
                <h3 class="margin-custom", id="prix_produit"></h3>
                <p><a class="btn btn-lg btn-primary" role="button" onlick="">Ajouter au panier</a></p>
            </div>

        </div>
    </div>
    
    <div class="row">
        <div class="col">
            <h4>Description Du Produit</h3>
            <p id="description_produit"></p>
        </div>
    </div>

</div>