<h1 class="h3 mb-3 font-weight-normal text-center">Inscription</h1>

<form>
    <div class="form-row row">    
        <div class="form-group col-md-4 col-centered">
            <label for="inputFirstName">Prénom</label>
            <input type="text" id="inputFirstName" class="form-control" placeholder="" required>
        </div>
    </div> 

    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputLastName">Nom</label>
            <input type="text" id="inputLastName" class="form-control" placeholder="" required>
        </div>
    </div> 

    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputAddress">Adresse</label>
            <input type="text" id="inputAddress" class="form-control" placeholder="" required>
        </div>
    </div> 

    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputZipCode">Code Postal</label>
            <input type="text" id="inputZipCode" class="form-control" placeholder="" required>
        </div>
    </div> 

    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputTown">Ville</label>
            <input type="text" id="inputTown" class="form-control" placeholder="" required>
        </div>
    </div> 

    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputCountry">Pays</label>
            <input type="text" id="inputCountry" class="form-control" placeholder="" required>
        </div>
    </div> 
    
    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputEmail">Email</label>
            <input type="text" id="inputEmail" class="form-control" placeholder="" required>
        </div>
    </div> 

    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputUsername">Nom d'utilisateur</label>
            <input type="text" id="inputUsername" class="form-control" placeholder="" required>
        </div>   
    </div> 
    
    <div class="form-row row"> 
        <div class="form-group col-md-4 col-centered">
            <label for="inputPassword">Mot de passe</label>
            <input type="password" id="inputPassword" class="form-control" placeholder="" required>
        </div>
    </div>  

    <div class="form-row row">  
        <div class="form-group col-md-3 col-centered">
            <button class="btn btn-lg btn-primary btn-block" type="button" onclick="signup_callback()" >S'inscrire</button>
        </div>
    </div>
</form>